import { mkdir } from 'node:fs/promises';
import { spawn } from 'node:child_process';

const reportSteps = [
  'molecule:coordinates',
  'molecule:calibration',
  't1:coupling',
  't1:sweep',
  't1:stability',
  't1:refine',
  'molecule:peroxide-refine',
  'molecule:peroxide-release-sensitivity',
  'molecule:peroxide-release-predeclare',
  'molecule:peroxide-target-reserve',
  'molecule:peroxide-source-lock',
  'molecule:peroxide-source-extract',
  'molecule:peroxide-ch3ooh-diagnostic',
  'molecule:peroxide-substituted-predeclare',
  'molecule:peroxide-ethyl-source-lock',
  'molecule:peroxide-ethyl-hint',
  'molecule:peroxide-ethyl-source-extract',
  'molecule:peroxide-ethyl-score',
  'molecule:peroxide-torsion',
  'molecule:ethane-torsion',
  'molecule:ionic-lattice',
  'material:silicate-network',
  'material:mixed-modifier',
  'material:nbo-stoichiometry',
  'interface:boundary-transition',
  'interface:phase-continuity',
  'interface:roughness-scatter',
  'model:assumptions',
  'model:external-roadmap',
  'benchmark:h2o2',
  'model:parameter-experiments',
  'benchmark:h2o2-quant',
  'benchmark:ethane',
  'benchmark:ethane-quant',
  'benchmark:h2o2-absolute',
  'molecule:peroxide-promotion-review',
  'molecule:peroxide-dual-channel-predeclare',
  'molecule:peroxide-dual-channel-diagnostic',
  'molecule:peroxide-dual-channel-reserve',
  'molecule:peroxide-dimethyl-source-lock',
  'molecule:peroxide-observable-route-predeclare',
  'molecule:peroxide-observable-route-diagnostic',
  'molecule:peroxide-observable-route-reserve',
  'molecule:peroxide-diethyl-source-lock',
  'molecule:peroxide-source-availability',
  'molecule:peroxide-tbhp-reserve',
  'molecule:peroxide-tbhp-source-lock',
  'molecule:peroxide-tbhp-source-extract',
  'molecule:peroxide-tbhp-score',
  'molecule:peroxide-intermediate-availability',
  'molecule:peroxide-peroxyformic-reserve',
  'molecule:peroxide-peroxyformic-source-lock',
  'molecule:peroxide-peroxyformic-score',
  'molecule:peroxide-relative-crowding-predeclare',
  'molecule:peroxide-relative-crowding-diagnostic',
  'molecule:peroxide-evidence-policy',
  'molecule:peroxide-v2-target-reserve',
  'molecule:peroxide-hmhp-source-lock',
  'molecule:peroxide-v2-source-availability',
  'molecule:peroxide-methyl-chloro-reserve',
  'molecule:peroxide-methyl-chloro-source-lock',
  'model:frontier',
  'benchmark:hydrazine-cation',
  'benchmark:neutral-hydrazine-reserve',
  'benchmark:neutral-hydrazine-source-lock',
  'benchmark:disulfane-prelookup',
  'benchmark:disulfane-comparison',
  'benchmark:selenane-prelookup',
  'benchmark:selenane-comparison',
  'diagnostic:heteroatom-trans-repair',
  'benchmark:ionic',
  'benchmark:boundary-blind',
  'benchmark:em-ordering',
  'benchmark:em-coulomb',
  'benchmark:em-superposition',
  'benchmark:em-three-source',
  'benchmark:em-field-lines',
  'benchmark:em-equipotential',
  'benchmark:em-field-magnitude',
  'benchmark:em-dielectric-media',
  'benchmark:em-wave-propagation',
  'benchmark:em-boundary-propagation',
  'benchmark:em-oblique-fresnel',
  'benchmark:em-multilayer-interference',
  'benchmark:em-absorbing-media',
  'benchmark:em-rough-surface-scatter',
  'benchmark:em-diffraction-grating',
  'benchmark:em-single-slit-envelope',
  'benchmark:em-double-slit-envelope',
  'benchmark:silicate-heldout',
  'benchmark:roughness-heldout',
  'benchmark:material-nbo',
  'benchmark:material-refractive-index',
  'benchmark:ri-cation-response',
  'benchmark:roughness-calibrated-scatter',
  'benchmark:roughness-psd-brdf-predeclare',
  'benchmark:roughness-tungsten-reserve',
  'benchmark:roughness-tungsten-source-lock',
  'benchmark:roughness-source-screen',
  'benchmark:roughness-tayabaly-reserve',
  'benchmark:roughness-tayabaly-source-lock',
  'benchmark:roughness-psd-cross-predeclare',
  'benchmark:roughness-psd-brdf-feasibility',
  'benchmark:summary',
  'milestone:external-review',
  'review:claude-drift-completeness',
];

await mkdir(new URL('../analysis/out/', import.meta.url), { recursive: true });

for (const step of reportSteps) {
  await run('npm', ['run', step]);
}

function run(command, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { stdio: 'inherit', shell: false });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`${command} ${args.join(' ')} exited with ${code}`));
      }
    });
  });
}
